import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const nova_round = localFont({
  src: "./fonts/NovaRound-Regular.ttf",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nova_round.className}`}>
        {children}
      </body>
    </html>
  );
}
